version: '3.8'
services:
  database:
    container_name: database_pg
    image: postgres:14.3-alpine3.15
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local